version: '3.8'
services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - database
      - kafka
    ports:
      - '8888:8888'

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - '3006:3005'
    volumes:
      - ./ui/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ui/public/index.html:/usr/share/nginx/html/index.html
      - ./ui/public/css:/usr/share/nginx/html/css

  database:
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=documents
    volumes:
      - /var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
      - ZOOKEEPER_TICK_TIME=2000
    ports:
      - '22181:2181'

  kafka:
    image: confluentinc/cp-kafka:latest
    ports:
      - '19092:19092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:19092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - zookeeper
